### ISSUE TITLE
Look how to pass command line options into the container when the container is launched

### ISSUE THREAD

**Issue by Maresther-B** [Esthenia-collaboration/rfswarm-docker#12]
When this will be figure out, we'll remove the options set in the dockerfile. That way people could decide what options they want to pass to run their docker agent.

**Comment by damies13** [comment]
I think you've solved this in PR #17

**Comment by Maresther-B** [comment]
> I think you've solved this in PR [#17](https://github.com/Esthenia-collaboration/rfswarm-docker/pull/17)

Yeah Indeed.I'll close this issue
