### ISSUE TITLE
Identify the default command lines options we'll add in the agent docker base image

### ISSUE THREAD

**Issue by Maresther-B** [Esthenia-collaboration/rfswarm-docker#18]
Ask Dave to give us all the prerequisite mandatory command lines options needed by a user to correctly run the agent.
Is the manager's URL sufficient or are there other command line which could be add by default

**Comment by damies13** [comment]
All the command line options are optional.

The way rfswarm works, based on a settings priority order
- setting value defined with default internal value
- if setting in ini file over-ride internal value with ini file value
- if a command line option is set it is over-ride internal value with command line option value

The only reason you need to specify the manager's URL, is the default internal value is http://localhost:8138/ which will never connect.

The way you have configured the base image to now take any arguments the user passes is perfect.

The default agent name is the hostname, on docker containers this is a random string of numbers and letters, you can use the `-a` option to set the agent name the same as the container name e.g. I did this (but it's completely optional):
```
docker run --rm --name agent00 -d ghcr.io/esthenia-collaboration/rfswarm-base-image:latest -m http://hp-elite-desk-800-g3:8138 -a agent00
docker run --rm --name agent01 -d ghcr.io/esthenia-collaboration/rfswarm-base-image:latest -m http://hp-elite-desk-800-g3:8138 -a agent01
docker run --rm --name agent02 -d ghcr.io/esthenia-collaboration/rfswarm-base-image:latest -m http://hp-elite-desk-800-g3:8138 -a agent02
```

**Comment by damies13** [comment]
After further thought on this it might be a good idea to us the custom property option in the defaults
```
-p PROPERTY, --property PROPERTY
                        Add a custom property, if multiple properties are required use this argument for each property e.g. -p property1 -p "Property 2"
```
I'll suggest adding this: `-p container:docker`

That was people can apply an agent filter to their test groups based on if the agent is a running on docker or not.

In the future I hope to provide LXC containers (for proxmox users) so for thise I'll add `-p container:lxc`

**Comment by Maresther-B** [comment]
> After further thought on this it might be a good idea to us the custom property option in the defaults
> 
> ```
> -p PROPERTY, --property PROPERTY
>                         Add a custom property, if multiple properties are required use this argument for each property e.g. -p property1 -p "Property 2"
> ```
> 
> I'll suggest adding this: `-p container:docker`
> 
> That was people can apply an agent filter to their test groups based on if the agent is a running on docker or not.
> 
> In the future I hope to provide LXC containers (for proxmox users) so for thise I'll add `-p container:lxc`

Ok Dave, thanks for your reply. But I have a little question, can you please remind me what's the use of properties. I can't remember , I need I quick refresher for this

**Comment by damies13** [comment]
The main purpose of the agent property is for the agent filter setting, used to control which agents a test can or can't run on

https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#agent-filter

**Comment by Maresther-B** [comment]
> The main purpose of the agent property is for the agent filter setting, used to control which agents a test can or can't run on
> 
> https://github.com/damies13/rfswarm/blob/master/Doc/rfswarm_manager.md#agent-filter

Yeah , I remember now. I use to used it before. Thanks Dave for the reminder

**Comment by Maresther-B** [comment]
@KseniaYa Can I affect you the issue to finalize de command line option part please?

**Comment by Maresther-B** [comment]
I think issue has been already implemented by @KseniaYa? didn't it?
