### ISSUE TITLE
Fix permission denied error

### ISSUE THREAD

**Issue by KseniaYa** [Esthenia-collaboration/rfswarm-docker#24]
run:
`docker run --rm docker.io/estheniacollaboration/rfswarm-agent-base-image:latest`

error:
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/opt/bin/entrypoint.sh": permission denied: unknown.

**Comment by Maresther-B** [comment]
The bug has been fixed by Ksenia modification
